# Generated by Django 5.1.2 on 2025-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type_name', models.CharField(max_length=100)),
                ('used_car_model', models.ManyToManyField(to='car.carmodel')),
            ],
        ),
    ]
